# Generated by Django 2.1.7 on 2019-02-14 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, null=True)),
                ('link_plano_pedagogico', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('cod_disc', models.AutoField(primary_key=True, serialize=False)),
                ('nome_disc', models.CharField(max_length=40)),
                ('desc_disc', models.CharField(max_length=90)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='siga_api.Curso')),
                ('pre_requisitos', models.ManyToManyField(to='siga_api.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='GradeDeAulas',
            fields=[
                ('cod_grade_aulas', models.IntegerField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=10)),
                ('formula', models.CharField(blank=True, max_length=40, null=True)),
                ('cod_disc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='siga_api.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Leciona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=15, null=True)),
                ('cod_grade_aulas', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='siga_api.GradeDeAulas')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=40)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('dt_nasc', models.DateField(blank=True, null=True)),
                ('email_institucional', models.CharField(blank=True, max_length=80, null=True)),
                ('senha', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='siga_api.Pessoa')),
                ('ra', models.CharField(max_length=13)),
            ],
            bases=('siga_api.pessoa',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='siga_api.Pessoa')),
                ('rm', models.CharField(max_length=14)),
                ('email_contato', models.CharField(blank=True, max_length=80, null=True)),
            ],
            bases=('siga_api.pessoa',),
        ),
        migrations.AddField(
            model_name='leciona',
            name='cpf_prof',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='siga_api.Professor'),
        ),
        migrations.AddField(
            model_name='curso',
            name='coordenador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='siga_api.Professor'),
        ),
        migrations.AlterUniqueTogether(
            name='leciona',
            unique_together={('cpf_prof', 'cod_grade_aulas')},
        ),
    ]
