# Generated by Django 2.1.7 on 2019-02-27 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siga_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('grade_aulas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='siga_api.GradeDeAulas')),
            ],
        ),
    ]
